Ta_200:
  description: Air temperature at 2 meters above ground
  unit: °C (degree Celcius, -40 to 60)

Ta_200_min:
  description: Minimum value of Ta_200
  unit: °C (degree Celcius, -40 to 60)

Ta_200_max:
  description: Maximum value of Ta_200
  unit: °C (degree Celcius, -40 to 60)
  
rH_200:
  description: Relative air humidity at 2 meters above ground
  unit: % (percentage of relative humidity, 0-100) 
  
rH_200_min:
  description: Minimum value of rH_200
  unit: % (percentage of relative humidity, 0-100)

rH_200_max:
  description: Maximum value of rH_200
  unit: % (percentage of relative humidity, 0-100)

Ta_10:
  description: Air temperature 10 centimeters above surface within the ground vegetation layer
  unit: °C (degree Celcius, -40 to 60) 

Ts_5:
  description: Soil temperature at 5 centimeters below surface
  unit: °C (degree Celcius, -40 to 60) 

Ts_10:
  description: Soil temperature at 10 centimeters below surface 
   unit: °C (degree Celcius, -40 to 60) 
 
Ts_20: 
  description: Soil temperature at 20 centimeters below surface 
  unit: °C (degree Celcius, -40 to 60) 

Ts_50:
  description: Soil temperature at 50 centimeters below surface
  unit: °C (degree Celcius, -40 to 60) 

SM_10:
  description: Soil moisture at 10 centimeters below surface
  unit: % (percentage of volumetric water content) 

SM_15:
  description: Soil moisture at 15 centimeters below surface (BeCycles sensor type at Exploratories) 
  unit: % (percentage of volumetric water content) 

SM_20:
  description: Soil moisture at 20 centimeters below surface
   unit: % (percentage of volumetric water content) 
 
SM_30: 
  description: Soil moisture at 30 centimeters below surface (BeCycles sensor type at Exploratories) 
  unit: % (percentage of volumetric water content) 

SM_40:
  description: Soil moisture at 40 centimeters below surface (BeCycles sensor type at Exploratories)
   unit: % (percentage of volumetric water content) 
  
SM_50:   
  description: Soil moisture at 50 centimeters below surface (BeCycles sensor type at Exploratories) 
  unit: % (percentage of volumetric water content) 

#****** new BeCycles sensors ********

SM_10_2:
  description: Soil moisture at 10 centimeters below surface (BeCycles sensor type at Exploratories)
   unit: % (percentage of volumetric water content) 
  
SM_20_2:
  description: Soil moisture at 20 centimeters below surface (BeCycles sensor type at Exploratories)
  unit: % (percentage of volumetric water content) 
  
SM_35:
  description: Soil moisture at 35 centimeters below surface (BeCycles sensor type at Exploratories)
   unit: % (percentage of volumetric water content) 
  
#************************************

PAR_200:
  description: Photosynthetically activ radiation at 2 meters height
  unit: µmol/(m^2*s) (micromol photons per square meter per second)

PAR_300:
  description: Photosynthetically activ radiation at 3 meters height
  unit: µmol/(m^2*s) (micromol photons per square meter per second) 
   
Albedo:
  description: Albedo (SWUR/SWDR)
  unit: ratio (0 to 1) 
   
SWDR_300:
  description: Shortwave Downward Radiation at 3 meters height
  unit: kWh/m^2 (kilo watt hour per square meter) 
   
SWUR_300:
  description: Shortwave Upward Radiation at 3 meters height
  unit: kWh/m^2 (kilo watt hour per square meter) 
   
LWDR_300:
  description: Longwave Downward Radiation at 3 meters height
  unit: kWh/m^2 (kilo watt hour per square meter) 
   
LWUR_300:
  description: Longwave Upward Radiation at 3 meters height
  unit: kWh/m^2 (kilo watt hour per square meter) 
   
Rn_300:
  description: Net radiation at 3 meters height
  unit: kWh/m^2 (kilo watt hour per square meter) 
   
Tsky:
  description: Sky temperature
   unit: °C (degree Celcius) 
  
Tgnd:
  description: Ground temperature
  unit: °C (degree Celcius) 
   
Trad:
  description: Radiation temperature
  unit: °C (degree Celcius) 
   
WD:
  description: Wind direction
  unit: ° (degree of arc 0-360) 
  
WV:
  description: Wind velocity
  unit: m/s (meter per second) 
  
WV_gust:
  description: Max. wind velocity (gust of wind)
  unit: m/s (meter per second) 
  
p_QNH:
  description: Barometric pressure QNH/MSL, adjusted to mean sea level
   unit: hPa (hectopascal)
  
p_local:
  description: Barometric pressure, local
  unit: hPa (hectopascal)
   
P_RT_NRT:
  description: Precipitation
  unit: mm (millimeter) 
   
P_container_RT:
  description: Precipitation, actual unfiltered amount in container
   unit: mm (millimeter) 
  
P_container_NRT:
  description: Precipitation, actual filtered amount in container   
  unit: mm (millimeter) 

#general radiation

SWDR:
  description: Shortwave Downward Radiation
  unit: kWh/m^2 (kilo watt hour per square meter) 
  
SWUR:
  description: Shortwave Upward Radiation
  unit: kWh/m^2 (kilo watt hour per square meter) 
  
LWDR:
  description: Longwave Downward Radiation
  unit: kWh/m^2 (kilo watt hour per square meter) 
  
LWUR:
  description: Longwave Upward Radiation
  unit: kWh/m^2 (kilo watt hour per square meter) 

#****** new sensors in AET06 ********

SWDR_3700:
  description: Shortwave Downward Radiation at 37 meters height
  unit: kWh/m^2 (kilo watt hour per square meter) 
  
SWUR_3700:
  description: Shortwave Upward Radiation at 37 meters height
  unit: kWh/m^2 (kilo watt hour per square meter) 
  
LWDR_3700:
  description: Longwave Downward Radiation at 37 meters height
  unit: kWh/m^2 (kilo watt hour per square meter)
  
LWUR_3700:
  description: Longwave Upward Radiation at 37 meters height
  unit: kWh/m^2 (kilo watt hour per square meter)
  
PAR_2000:
  description: Photosynthetically activ radiation at 20 meters height
   unit: µmol/(m^2*s) (micromol photons per square meter per second) 
 
PAR_1000:
  description: Photosynthetically activ radiation at 10 meters height
  unit: µmol/(m^2*s) (micromol photons per square meter per second) 
  
Ta_1000:
  description: Air temperature at 10 meters above ground
  unit: °C (degree Celcius, -40 to 60) 
  
rH_1000:
  description: Relative air humidity at 10 meters above ground
  unit: % (percentage of relative humidity, 0-100)
  
Ta_2000:
  description: Air temperature at 20 meters above ground
  unit: °C (degree Celcius, -40 to 60) 
 
rH_2000:
  description: Relative air humidity at 20 meters above ground
  unit: % (percentage of relative humidity, 0-100) 
  
Ta_3000:
  description: Air temperature at 30 meters above ground
  unit: °C (degree Celcius, -40 to 60)
  
rH_3000:
  description: Relative air humidity at 30 meters above ground
  unit: % (percentage of relative humidity, 0-100) 
 
Ta_3700: °C (degree Celcius, -40 to 60)
  description: Air temperature at 37 meters above ground
  unit: 
  
rH_3700:
  description: Relative air humidity at 37 meters above ground
  unit: % (percentage of relative humidity, 0-100)

#added 2016_03_08
Rn_3700:
  description: Net radiation at 37 meters height
  unit: kWh/m^2 (kilo watt hour per square meter)

#****** new sensors in SET39 ********

SWDR_4400:
  description: Shortwave Downward Radiation at 44 meters height
  unit: kWh/m^2 (kilo watt hour per square meter) 
  
SWUR_4400:
  description: Shortwave Upward Radiation at 44 meters height
  unit: kWh/m^2 (kilo watt hour per square meter) 
  
LWDR_4400:
  description: Longwave Downward Radiation at 44 meters height
  unit: kWh/m^2 (kilo watt hour per square meter) 
  
LWUR_4400:
  description: Longwave Upward Radiation at 44 meters height
  unit: kWh/m^2 (kilo watt hour per square meter) 
 
Ta_4400:
  description: Air temperature at 44 meters above ground
  unit: °C (degree Celcius, -40 to 60) 
 
rH_4400:
  description: Relative air humidity at 44 meters above ground
  unit: % (percentage of relative humidity, 0-100) 

#added 2016_03_08
Rn_4400:
  description: Net radiation at 44 meters height
  unit: kWh/m^2 (kilo watt hour per square meter) 


#****** Kili Sensors ********** (sensors that are not in BE)

p_200:
  description: Barometric pressure at 2 meters above ground
  unit: hPa (hectopascal)
  
T_CNR:
  description: (T_CNR)
  unit: [T_CNR]
 
P_RT_NRT_01:
  description: Precipitation
  unit: mm (millimeter)
 
P_RT_NRT_02:
  description: Precipitation
  unit: mm (millimeter)
  
F_RT_NRT_01:
  description: Fog
  unit: mm (millimeter)
  
F_RT_NRT_02:
  description: Fog
  unit: mm (millimeter)
  
T_RT_NRT_01:
  description: (T_RT_NRT_01)
  unit: mm (millimeter)
  
T_RT_NRT_02:
  description: (T_RT_NRT_02)
  unit: mm (millimeter)
  
par_01:
  description: Photosynthetically active radiation
  unit: µmol/(m^2*s) (micromol photons per square meter per second) 
  
par_02:
  description: Photosynthetically active radiation
  unit: µmol/(m^2*s) (micromol photons per square meter per second) 
  
swdr_01:
  description: Shortwave downward radiation
  unit: kWh/m^2 (kilo watt hour per square meter)
  
swdr_02:
  description: Shortwave downward radiation
  unit: kWh/m^2 (kilo watt hour per square meter)
  
B_01:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements) 
  
B_02:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_03:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_04:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_05:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_06:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_07:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_08:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_09:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_10:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_11:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_12:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
 
B_13:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_14:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_15:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_16:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_17:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_18:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_19:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_20:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_21:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_22:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_23:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_24:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_25:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_26:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_27:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_28:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_29:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
B_30:
  description: Specific precipitation measurement
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
Fog:
  description: Fog
  unit: mm (millimeter) (based on approx. weekly measurements)  
  
Rainfall:
  description: Precipitation
  unit: mm (millimeter) (based on approx. weekly measurements)  

#************* south africa sensors at own stations *********

DecagonECH2O:
  description: Soil moisture
  unit: mV (millivolt) 

#************* isotope sensors at kili tfi *********

fog_d18_16:
  description: fog isotope ratio d<sup>18</sup>O = <sup>18</sup>O/<sup>16</sup>O  relative to VSMOW (Vienna Standard Mean Ocean Water)
  unit: ratio
  
fog_dD_H:
  description: fog isotope ratio dD = deuterium/protium  relative to VSMOW (Vienna Standard Mean Ocean Water)
  unit: ratio 
  
fog_d_excess:
  description: fog deuterium excess d = dD - 8d<sup>18</sup>O
  unit:  ratio

rain_d18_16:
  description: rain isotope ratio d<sup>18</sup>O = <sup>18</sup>O/<sup>16</sup>O  relative to VSMOW (Vienna Standard Mean Ocean Water)
  unit: ratio 
  
rain_dD_H:
  description: rain isotope ratio dD = deuterium/protium  relative to VSMOW (Vienna Standard Mean Ocean Water)
  unit: ratio 
  
rain_d_excess:
  description: rain deuterium excess d = dD - 8d<sup>18</sup>O
  unit: ratio 

tf_d18_16:
  description: thrufall isotope ratio d<sup>18</sup>O = <sup>18</sup>O/<sup>16</sup>O  relative to VSMOW (Vienna Standard Mean Ocean Water)
  unit: ratio 
 
tf_dD_H:
  description: thrufall isotope ratio dD = deuterium/protium  relative to VSMOW (Vienna Standard Mean Ocean Water)
  unit: ratio 
  
tf_d_excess:
  description: thrufall deuterium excess d = dD - 8d<sup>18</sup>O
  unit: ratio 

#************* virtual sensors for exploratories *********

SD:
  description: sunshine duration (time of radiation >= 120 W/m^2)
  unit: h (hour) 

#new sensors 2015_01_27 south africa own (station 10)

dew_point:
  description: dew point temperature
  unit: °C (degree Celcius, -40 to 60) 
  
absH_200:
  description: Absolute air humidity at 2 meters above ground
  unit: g/m^3 (gram per cubic meter) 
  
wet_bulb_temp:
  description: Wet-bulb temperature  
  unit: °C (degree Celcius, -40 to 60) 
  