- {station: AEG01, start: 2015-05-12, end: 2016-06-17, content: {label: CNR4, SWDR: 13.67, SWUR: 16.82, LWDR: 9.74, LWUR: 10.93} }
- {station: AEG11, start: 2014-06-05, end: 2016-06-20, content: {label: CNR4, SWDR: 17.38, SWUR: 16.88, LWDR: 10.89, LWUR: 10.01} }

- {station: AEG01, start: "2016-06-18T14:20", content: {label: computation, target: PAR_300, formula: "PAR_300_U * 1000 / 5.59", comment: "2017-04-07 calculate missing PAR_300 values"}}

- {station: HEG19, start: "2016-12", content: {label: computation, target: PAR_300_U, formula: "PAR_300_U - 2.1", comment: "2017-04-10 corrected offset"}}
- {station: HEG19, start: "2016-12", content: {label: computation, target: PAR_300, formula: "PAR_300_U * 1000 / 5.33", comment: "2017-04-10 recalculate PAR_300 values (with corrected offset)"}}

- {station: HEG03, end: "2013-07-31T16:40", content: {label: CNR4, SWDR: 19.87, SWUR: 17.05, LWDR: 8.74, LWUR: 9.99, comment: "2017-04-11 recalculate with corrected factors"} }
- {station: SEG03, end: "2013-09-06T12:30", content: {label: CNR4, SWDR: 17.63, SWUR: 16.69, LWDR: 8.98, LWUR: 8.59, comment: "2017-04-11 recalculate with corrected factors"} }

- {station: HET38, content: {label: computation, target: p_QNH, formula: "p_local * ( 1 - (0.0065 * (439+44)) / (Ta_200 + 0.0065 * (439+44) + 273.15) )^(-5.257)", comment: "local pressure to sea level pressure"}}
- {station: HET44, content: {label: computation, target: p_QNH, formula: "p_local * ( 1 - (0.0065 * (451+44)) / (Ta_200 + 0.0065 * (451+44) + 273.15) )^(-5.257)", comment: "local pressure to sea level pressure"}}

- {station: HEG48, start: "2017-06-26T13:00", end: "2017-06-28T12:00", content: {label: CNR4, SWDR: 15.82, SWUR: 18.63, LWDR: 9.28, LWUR: 10.64, comment: "2017-07-05 recalculate with corrected factors"} }

