title: Environmental Informatics Lab
baseurl: "/tubedb" # the subpath of your site, e.g. /blog
url: "https://environmentalinformatics-marburg.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  environmentalinformatics-marburg
repository: 'environmentalinformatics-marburg/tubedb'

markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.16.3"
plugins:
  - jekyll-include-cache
  - jekyll-feed

minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

logo: "/assets/images/logo_umr.png"
search: true
search_full_content: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/environmentalinformatics-marburg/tubedb"

include:
  - _pages
  
collections:
  documentation:
    output: true
    permalink: /:collection/:title/
  usage:
    output: true
    permalink: /:collection/:title/
  configuration:
    output: true
    permalink: /:collection/:title/ 
  api:
    output: true
    permalink: /:collection/:title/         

defaults:
  - scope:
      path: ""
      type: documentation
    values:
      layout: single
      classes: wide
      author_profile: false
      sidebar:
        nav: "docs"

  - scope:
      path: ""
      type: usage
    values:
      layout: single
      classes: wide
      author_profile: false
      sidebar:
        nav: "docs" 
        
  - scope:
      path: ""
      type: configuration
    values:
      layout: single
      classes: wide
      author_profile: false
      sidebar:
        nav: "docs" 
        
  - scope:
      path: ""
      type: api
    values:
      layout: single
      classes: wide
      author_profile: false
      sidebar:
        nav: "docs"  
